name=DAC8568
version=0.1.0
author=Sukanta Das <das.sukanta2praha@gmail.com>
maintainer=Sukanta Das <das.sukanta2praha@gmail.com>
sentence=Driver for the TI DAC8568/DAC8168/DAC7568 16/14/12-bit, 8-channel SPI DAC.
category=Signal Input/Output
url=https://github.com/sukanta0011/DAC8568
architectures=*
includes=DAC8568.h